version: '2'
services:
  site:
    container_name: grav
    image: grav
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=Pa55word
      - ADMIN_EMAIL=admin@adventureinliving.co.uk
      - ADMIN_PERMISSIONS=b
      - ADMIN_FULLNAME=Admin
      - ADMIN_TITLE=SiteAdmin
      - DOMAIN=adventureinliving.co.uk
      - GENERATE_CERTS=false
    volumes:
      - backup:/var/www/grav-admin
volumes:
  backup:
    external: false
